### ISSUE TITLE
[BUG] - docker hub ubuntu images without entypoint

### ISSUE THREAD

**Issue by blaggacao** [jitesoft/docker-keybase-sshca#1]
check:

`docker run --entrypoint="" jitesoft/keybase-sshca:latest-alpine ls /usr/local/bin | grep entrypoint`
VS
`docker run --entrypoint="" jitesoft/keybase-sshca:latest ls /usr/local/bin | grep entrypoint`

Might be true for other images as well...

Thanks for this project's great help (especially with ARM build!!!)

**Comment by Johannestegner** [comment]
Thank you for the report! I will take a look after my morning meeting on current contract! ;)

Happy you like the Images, always nice to see someone using them (except from me) hehe :)

**Comment by Johannestegner** [comment]
I have located the issue. For some reason, the entrypoint script is inside the /usr/bin and not /usr/local/bin, due to this, it's not chmod +x'ed in the RUN command and therefore not usable!

A fix is being pushed as speaking! (will close this issue when I have verified it as I don't have a local ARM server, hehe).

**Comment by Johannestegner** [comment]
Alright, tested and up. Should work and is now latest version. Let me know if there are any issues and happy ssh'ing! :)

**Comment by blaggacao** [comment]
I have to recognize, your images have saved me 2-3 days of additional trial and error. They seem very solid and with usability and clarity in mind, as opposed to the official docker tooling which seems to do everything different than what people might be used to see...

Actually there is a segfault issue, on RPI arm, I reported in keybase-ssh, but since it might be arm specific, and thus related to the build, I'll open an issue here to to link said issue.

Thanks again for your quick fix!

Hosting this thing on a rpi is the perfect breakglass appliance: just plug it out.

**Comment by Johannestegner** [comment]
I only have virtual aarch64 systems sadly (should really buy a few extra pi3/4 for that!), so all I can test on is my Aarch64 build server and via qemu. But the image that is up now ran fine on my server, so please test it and see if it helps with the segfault too, if it does not I will happily take a more deep dive in it and see if I can find the issue. One of the reasons I try to push images for aarch64 is due to the rpi availability, so it _should_ work for it imo! :)
